name       : sc-im
version    : 0.8.2
release    : 2
source     :
    - https://github.com/andmarti1424/sc-im/archive/refs/tags/v0.8.2.tar.gz : 7f00c98601e7f7709431fb4cbb83707c87016a3b015d48e5a7c2f018eff4b7f7
license    : BSD-4-Clause
component  : office
summary    : SC-IM - Spreadsheet Calculator Improvised -- An ncurses spreadsheet program for the terminal
description: |
    Terminal-based spreadsheet program with vi-like key bindings
environment: |
    export CFLAGS="${CFLAGS} -fcommon"
setup      : |
    sed -i 's/\/usr\/local/\/usr/g' src/Makefile
build      : |
    %make -C src
install    : |
    %make_install -C src
