name       : sc-im
version    : 0.7.0
release    : 1
source     :
    - https://github.com/andmarti1424/sc-im/archive/v0.7.0.tar.gz : 87225918cb6f52bbc068ee6b12eaf176c7c55ba9739b29ca08cb9b6699141cad
license    : BSD-4-Clause
component  : office
summary    : SC-IM - Spreadsheet Calculator Improvised -- An ncurses spreadsheet program for the terminal
description: |
    Terminal-based spreadsheet program with vi-like key bindings
setup      : |
    sed -i 's/\/usr\/local/\/usr/g' src/Makefile
build      : |
    %make -C src
install   : |
    %make_install -C src
